# https://crates.io/crates/grcov

[env]
COVERAGE_WORKING_DIRECTORY = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/coverage"
COVERAGE_BINARIES = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/debug"
COVERAGE_PROF_OUTPUT = "${COVERAGE_WORKING_DIRECTORY}/profraw"

[tasks.coverage-grcov-prepare-outdir]
private = true
script='''
#!/usr/bin/env bash
set -eux

rm -rf ${COVERAGE_PROF_OUTPUT}
mkdir -p ${COVERAGE_PROF_OUTPUT}
'''

[tasks.coverage-grcov-run-test]
condition = { rust_version = { min = "1.60.0" } }
private = true
run_task = "test"

[tasks.coverage-grcov-run-test.env]
CARGO_INCREMENTAL = "0"
RUSTFLAGS = "-Cinstrument-coverage"
LLVM_PROFILE_FILE = "${COVERAGE_PROF_OUTPUT}/coverage-%p-%m.profraw"

[tasks.install-grcov]
condition = { env_not_set = ["SKIP_INSTALL_GRCOV"] }
private = true
command = "cargo"
args = ["install", "grcov", "--version=0.9.1", "--locked"]

# NOTE: ignore coverage for swapper and zapper contracts because their tests are based on `osmosis-testing` which don't work for grcov
[tasks.coverage-grcov]
condition = { rust_version = { min = "1.60.0" } }
private = true
script = '''
#!/usr/bin/env bash
set -eux

grcov ${COVERAGE_PROF_OUTPUT} \
  -b ${COVERAGE_BINARIES} -s ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY} \
  -t ${GRCOV_OUTPUT_TYPE} --llvm --branch --ignore-not-existing --ignore "/*" --ignore "*/mock*" --ignore "*/tests/*" --ignore "*/testing/*" --ignore "target/*" --ignore "contracts/swapper/*" --ignore "*/zapper/*" -o ${GRCOV_OUTPUT_PATH}
'''
dependencies = ["install-grcov", "coverage-grcov-prepare-outdir", "coverage-grcov-run-test"]

[tasks.coverage-grcov-html]
env = { GRCOV_OUTPUT_TYPE = "html", GRCOV_OUTPUT_PATH = "${COVERAGE_WORKING_DIRECTORY}/html", TEST_RUNNER = "multi-test" }
run_task = "coverage-grcov"

[tasks.coverage-grcov-lcov]
env = { GRCOV_OUTPUT_TYPE = "lcov", GRCOV_OUTPUT_PATH = "${COVERAGE_WORKING_DIRECTORY}/lcov.info", TEST_RUNNER = "multi-test" }
run_task = "coverage-grcov"
