[package]
name = "mars-testing"
version = "0.1.0"
authors = [
  "Ahmad Kaouk <ahmad@delphilabs.io>",
  "Spike Spiegel <spikeonmars@protonmail.com>",
  "larry_0x <larry@delphidigital.io>",
  "Piotr Babel",
  "Harry Scholes"
]
edition = "2018"
description = "Utilities for testing Mars outpost contracts"
license = "GPL-3.0"
repository = "https://github.com/mars-protocol/mars-core"
homepage = "https://marsprotocol.io"
documentation = "https://docs.marsprotocol.io/mars-protocol/developers/protocol-overview"
readme = "README.md"
keywords = ["mars", "cosmwasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.0"
mars-outpost = { path = "../mars-outpost" }
osmo-bindings = { git = "https://github.com/osmosis-labs/bindings", tag = "v0.6.0" }
