[package]
name          = "mars-interest-rate"
description   = "Computations related to interest rates"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }
keywords      = { workspace = true }

[lib]
doctest = false

[features]
library = []

[dependencies]
cosmwasm-std    = { workspace = true }
mars-types      = { workspace = true }
