[package]
name = "mars-red-bank"
version = "0.1.0"
authors = [
  "larry_0x <larry@delphidigital.io>",
  "Piotr Babel <piotr@delphilabs.io>",
  "Spike Spiegel <spikeonmars@protonmail.com>",
  "Ahmad Kaouk",
  "Harry Scholes"
]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
mars-outpost = { path = "../../packages/outpost", version = "0.1.0" }
mars-health = { path = "../../packages/health", version = "0.1.0" }

cosmwasm-std = "1.1"
cw2 = "0.15"
cw-storage-plus = "0.15"
cw-utils = "0.15"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
mars-testing = { path = "../../packages/testing", version = "0.1.0" }

[profile.release]
overflow-checks = true
