[package]
name          = "mars-rewards-collector-base"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }
keywords      = { workspace = true }

[lib]
doctest = false

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std    = { workspace = true }
cw-storage-plus = { workspace = true }
mars-outpost    = { workspace = true }
schemars        = { workspace = true }
serde           = { workspace = true }
thiserror       = { workspace = true }
cw20 = { workspace = true }

[dev-dependencies]
cw20-base = { workspace = true }
mars-testing = { workspace = true }
