[package]
name          = "mars-rewards-collector"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }
keywords      = { workspace = true }

[lib]
crate-type = [
    "cdylib",
    "rlib",
]
doctest = false

[profile.release]
overflow-checks  = true

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = [
    "cosmwasm-std/backtraces",
]

[dependencies]
cosmwasm-schema     = { workspace = true }
cosmwasm-std        = { workspace = true, features = ["stargate"] }
cw-storage-plus     = { workspace = true }
mars-owner          = { workspace = true }
mars-red-bank-types = { workspace = true }
mars-utils          = { workspace = true }
schemars            = { workspace = true }
serde               = { workspace = true }
thiserror           = { workspace = true }

[dev-dependencies]
mars-osmosis = { workspace = true }
mars-testing = { workspace = true }
osmosis-std  = { workspace = true }
