[package]
name = "mars-revenue-collector-base"
version = "0.1.0"
authors = [
  "larry_0x <larry@delphidigital.io>",
  "Piotr Babel <piotr@delphilabs.io>",
  "Spike Spiegel <spikeonmars@protonmail.com>",
  "Ahmad Kaouk",
  "Harry Scholes"
]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
mars-outpost = { path = "../../../packages/outpost", version = "0.1.0" }

cosmwasm-std = { version = "1.0", features = ["stargate"] }
cw-storage-plus = "0.14"
schemars = "0.8"
serde = { version = "1.0.144", default-features = false, features = ["derive"] }
thiserror = "1.0.33"

[dev-dependencies]
mars-testing = { version = "0.1.0", path = "../../../packages/testing" }
