#[cfg(not(feature = "library"))]
pub mod contract;
pub mod error;
pub mod execute;
pub mod instantiate;
pub mod msg;
pub mod performance_fee;
pub mod query;
pub mod state;
pub mod token_factory;
pub mod vault_token;
