[package]
name          = "mars-swapper-base"
version       = { workspace = true }
authors       = { workspace = true }
license       = { workspace = true }
edition       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }
keywords      = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
overflow-checks  = true

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
library    = []

[dependencies]
cosmwasm-schema     = { workspace = true }
cosmwasm-std        = { workspace = true }
cw-paginate         = { workspace = true }
cw-storage-plus     = { workspace = true }
mars-owner          = { workspace = true }
mars-red-bank-types = { workspace = true }
schemars            = { workspace = true }
serde               = { workspace = true }
thiserror           = { workspace = true }
